### ISSUE TITLE
Problems testing NPM3D pretrained model

### ISSUE THREAD

**Issue by marialinea** [HuguesTHOMAS/KPConv-PyTorch#109]
Hello, 

Thank you for making your work available!

I have downloaded the pretrained model for the NPM3D dataset, along with the data. Both stored in the folder structure described in the repo. To my understanding there is no need for preprocessing the data, please correct me if I'm wrong. When I'm trying to run `test_any_model.py` I get the following error:

```console
Start Test
**********

2021-07-06 10:57:39.330305: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-06 10:57:40.226446: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
Traceback (most recent call last):
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/.env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/.env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/.env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: In[0] and In[1] must have compatible batch dimensions: [39,5958,128] vs. [15,128,128]
	 [[{{node KernelPointNetwork/layer_2/resnetb_deformable_0/conv2/MatMul_3}}]]
	 [[Softmax/_521]]
  (1) Invalid argument: In[0] and In[1] must have compatible batch dimensions: [39,5958,128] vs. [15,128,128]
	 [[{{node KernelPointNetwork/layer_2/resnetb_deformable_0/conv2/MatMul_3}}]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node KernelPointNetwork/layer_2/resnetb_deformable_0/conv2/MatMul_3:
 KernelPointNetwork/layer_2/resnetb_deformable_0/conv2/transpose_3 (defined at /nr/samba/jo/pro/autokart/usr/maria/kpconv/kernels/convolution_ops.py:490)

Input Source operations connected to node KernelPointNetwork/layer_2/resnetb_deformable_0/conv2/MatMul_3:
 KernelPointNetwork/layer_2/resnetb_deformable_0/conv2/transpose_3 (defined at /nr/samba/jo/pro/autokart/usr/maria/kpconv/kernels/convolution_ops.py:490)

Original stack trace for 'KernelPointNetwork/layer_2/resnetb_deformable_0/conv2/MatMul_3':
  File "test_any_model.py", line 277, in <module>
    test_caller(chosen_log, chosen_snapshot, on_val)
  File "test_any_model.py", line 135, in test_caller
    model = KernelPointFCNN(dataset.flat_inputs, config)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/models/KPFCNN_model.py", line 120, in __init__
    self.dropout_prob)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/models/network_blocks.py", line 1097, in assemble_FCNN_blocks
    F = assemble_CNN_blocks(inputs, config, dropout_prob)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/models/network_blocks.py", line 1065, in assemble_CNN_blocks
    training)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/models/network_blocks.py", line 414, in resnetb_deformable_block
    config)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/models/network_blocks.py", line 122, in KPConv_deformable
    modulated=config.modulated)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/kernels/convolution_ops.py", line 371, in KPConv_deformable
    aggregation_mode)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/kernels/convolution_ops.py", line 491, in KPConv_deform_ops
    kernel_outputs = tf.matmul(weighted_features, K_values)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/.env/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/.env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 3452, in matmul
    a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/.env/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1586, in batch_mat_mul_v2
    "BatchMatMulV2", x=x, y=y, adj_x=adj_x, adj_y=adj_y, name=name)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/.env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/.env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3565, in _create_op_internal
    op_def=op_def)
  File "/nr/samba/jo/pro/autokart/usr/maria/kpconv/.env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

```

I'm having problems identifying where the error occur, and how to remedy it given that I have not made any modification to the code, except changed `import tensorflow as tf` to `import tensorflow.compat.v1 as tf` since I'm running tensorflow 2.5.0.

Thanks in advance!
Maria

**Comment by marialinea** [comment]
Ah, this should be in the tensorflow version- sorry!
