### ISSUE TITLE
visualize_deformations "list index out of range"

### ISSUE THREAD

**Issue by d-serafly** [HuguesTHOMAS/KPConv-PyTorch#134]
Hi HuguesTHOMAS,
   Thank you for your implementaion of KPConv and sharing with us. When I finish train and test about Object Classification on ModelNet40, I run visualization scripts for the kernel deformations display, I meet this question. And I can't debug because my VNC Viewer of server conflicts with pyQT5. Could you give me some advice?

**QUESTION 1**
****************************************************
Run with SSH
****************************************************
Start visualization
*******************

List of the deformable convolution available (chosen one highlighted in green)

****************************************************

Traceback (most recent call last):
  File "visualize_deformations.py", line 199, in <module>
    visualizer.show_deformable_kernels(net, test_loader, config, deform_idx)
  File "/home/extend/gy/pyproject/KPConv-PyTorch-master/utils/visualizer.py", line 151, in show_deformable_kernels
    original_KP = deform_convs[deform_idx].kernel_points.cpu().detach().numpy()
IndexError: list index out of range
****************************************************

**QUESTION 2**
****************************************************
The error of Pycharm
****************************************************
qt.qpa.xcb: failed to initialize XRandr
qt.qpa.xcb: XKeyboard extension not present on the X server

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
****************************************************

**Comment by Ray8716397** [comment]
i have the same problem

**Comment by HuguesTHOMAS** [comment]
for the first bug, it seems the code does not see any deformable convolution in the network.

For the second bug, I cannot help much as it is not a question related to KPConv. Try to find a solution on StackOverflow or other sites like this by searching the sentence of the error "failed to initialize XRandr" or "XKeyboard extension not present on the X server"

**Comment by JunL-Geek** [comment]
so, how can i fix the first bug
