### ISSUE TITLE
ValueError: Truth values are stored in a 0D array instead of 1D array

### ISSUE THREAD

**Issue by DerekSunYH** [HuguesTHOMAS/KPConv-PyTorch#138]
Traceback (most recent call last):
  File "E:/3DPC/KPConv-PyTorch-master/train_SemanticKitti.py", line 324, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "E:\3DPC\KPConv-PyTorch-master\utils\trainer.py", line 274, in train
    self.validation(net, val_loader, config)
  File "E:\3DPC\KPConv-PyTorch-master\utils\trainer.py", line 292, in validation
    self.slam_segmentation_validation(net, val_loader, config)
  File "E:\3DPC\KPConv-PyTorch-master\utils\trainer.py", line 805, in slam_segmentation_validation
    Confs[i, :, :] = fast_confusion(truth, preds, val_loader.dataset.label_values).astype(np.int32)
  File "E:\3DPC\KPConv-PyTorch-master\utils\metrics.py", line 48, in fast_confusion
    raise ValueError('Truth values are stored in a {:d}D array instead of 1D array'. format(len(true.shape)))
ValueError: Truth values are stored in a 0D array instead of 1D array

Can somebody else tell me what happened?

**Comment by HuguesTHOMAS** [comment]
Seems you are providing an empty `truth` array in the confusion matrix function. 

You can try to track what happens by following the code backwards. The truth arrays come from here:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/73e444d486cd6cb56122c3dd410e51c734064cfe/utils/trainer.py#L781

So it is either `frame_labels` or `proj_mask` which is empty. I can't tell you much more without knowing what you modified in the code, the data, and the parameters. You can track this yourself and/or give me more details if you need more help.

**Comment by HyangXsea** [comment]
> Seems you are providing an empty array in the confusion matrix function.`truth`
> 
> You can try to track what happens by following the code backwards. The truth arrays come from here:
> 
> https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/73e444d486cd6cb56122c3dd410e51c734064cfe/utils/trainer.py#L781
> 
> So it is either or which is empty. I can't tell you much more without knowing what you modified in the code, the data, and the parameters. You can track this yourself and/or give me more details if you need more help.`frame_labels``proj_mask`

**Comment by HyangXsea** [comment]
Thanks. I had trained several times using semantikitii slam_segmentation, and the experiments with parameters you giving is normal. But when I change the KPConv parameters , such as first_subsampling_dl and num_kernel_points, it will raise `ValueError('Truth values are stored in a {:d}D array instead of 1D array'. format(len(true.shape)))` after training 200 epochs around.
I am so confused why the error occurs in the process of training instead of the begining.

**Comment by chenjt66a** [comment]
> Thanks. I had trained several times using semantikitii slam_segmentation, and the experiments with parameters you giving is normal. But when I change the KPConv parameters , such as first_subsampling_dl and num_kernel_points, it will raise `ValueError('Truth values are stored in a {:d}D array instead of 1D array'. format(len(true.shape)))` after training 200 epochs around. I am so confused why the error occurs in the process of training instead of the begining.

I meet the same problem after training 24 epochs, are there some solutions?

**Comment by magical1998** [comment]
> Thanks. I had trained several times using semantikitii slam_segmentation, and the experiments with parameters you giving is normal. But when I change the KPConv parameters , such as first_subsampling_dl and num_kernel_points, it will raise `ValueError('Truth values are stored in a {:d}D array instead of 1D array'. format(len(true.shape)))` after training 200 epochs around. I am so confused why the error occurs in the process of training instead of the begining.

Did you solve this problem,？I also had the same problem, but his elevation seems to happen randomly, sometimes after dozens of epochs, sometimes after a hundred
