### ISSUE TITLE
mapping values are not allowed in "semantic-kitti.yaml"

### ISSUE THREAD

**Issue by lixingyi8947** [HuguesTHOMAS/KPConv-PyTorch#15]
I got an error while loading "semantic-kitti.yaml" , line 122, column 73 which is shown below. Any suggestions? Thanks!

line 122: "span class="progress-pjax-loader-bar top-0 left-0" style="width: 0%;"></span"

Traceback (most recent call last):

  File "<ipython-input-2-e8489e9ef0c1>", line 52, in <module>
    balance_classes=True)

  File "/media/xingyi/Tools4TB/KPConv-PyTorch/datasets/SemanticKitti.py", line 103, in __init__
    doc = yaml.safe_load(stream)

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()

  File "/home/xingyi/miniconda3/envs/pointConv/lib/python3.7/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())

ScannerError: mapping values are not allowed here
  in "./Data/SemanticKitti/semantic-kitti.yaml", line 122, column 73

**Comment by HuguesTHOMAS** [comment]
I have no idea what happened here.

The error does not seem to come form a part of the code I wrote but from the yaml loader. Your `semantic-kitti.yaml` file might be corrupted. 

Maybe try to download this file again or open it in a text editor to see if something is wrong

**Comment by lixingyi8947** [comment]
Thanks! The .yaml file is broken.
