### ISSUE TITLE
Vaihingen _3D  data process problems

### ISSUE THREAD

**Issue by SC-shendazt** [HuguesTHOMAS/KPConv-PyTorch#160]
Hi Dr.HuguesTHOMAS  ,
![2](https://user-images.githubusercontent.com/74888508/164612667-74fa57d9-eeee-4fcb-9ce1-5e4eacfa508c.png)
![3](https://user-images.githubusercontent.com/74888508/164612679-0c25ec39-b522-4657-a786-a9fd07efd371.png)
The problem occurred after I changed very little code
Traceback (most recent call last):
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/train_NPM3D.py", line 304, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/utils/trainer.py", line 274, in train
    self.validation(net, val_loader, config)
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/utils/trainer.py", line 290, in validation
    self.cloud_segmentation_validation(net, val_loader, config)
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/utils/trainer.py", line 472, in cloud_segmentation_validation
    for i, batch in enumerate(val_loader):
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/datasets/NPM3D.py", line 257, in __getitem__
    return self.potential_item(batch_i)
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/datasets/NPM3D.py", line 318, in potential_item
    cloud_ind = int(torch.argmin(self.min_potentials))
RuntimeError: cannot perform reduction function argmin on a tensor with no elements because the operation does not have an identity

![QQ图片20220422135505](https://user-images.githubusercontent.com/74888508/164612210-d4b3208e-7a44-4633-8bef-1c1a054f6494.png)

**Comment by HuguesTHOMAS** [comment]
It seems to me that your data is not loaded.

First, you need to verify the preparation function:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/datasets/NPM3D.py#L650

It is a very simple function that loads the data, preprocesses it, and saves it in the right format for the rest of the pipeline. YOu should be able to read and understand it easily. Modify the line 

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/datasets/NPM3D.py#L691

with the name of any point cloud that does not contain labels. For the ones that contain labels, verify that the right name is given to read them (here it is 'class', but it could be something else):
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/datasets/NPM3D.py#L697

After this function you should have two .ply files `Vaihingen3D_train.ply` and  `Vaihingen3D_test.ply` in the ply_folder.

If everything works there and the error still happens, then you should verify the data loading function:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/datasets/NPM3D.py#L708

In that case tell me if you need help to understand it

**Comment by SC-shendazt** [comment]
Hello, Dr.HuguesTHOMAS, I verified ‘def prepare_NPM3D_ply(self): ’function as you said, and generated  two .ply files Vaihingen3D_train.ply and Vaihingen3D_test.ply in the train_folder.But there was a mistake at the end of round 0
![4](https://user-images.githubusercontent.com/74888508/164747586-e676d7f8-cee8-4fa8-b4ef-f0c6bb223bbf.png)

**Comment by HuguesTHOMAS** [comment]
What is the error message?

**Comment by SC-shendazt** [comment]
The error message is the same：
![Uploading 5.png…]()


Traceback (most recent call last):
File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/train_NPM3D.py", line 304, in
trainer.train(net, training_loader, test_loader, config)
File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/utils/trainer.py", line 274, in train
self.validation(net, val_loader, config)
File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/utils/trainer.py", line 290, in validation
self.cloud_segmentation_validation(net, val_loader, config)
File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/utils/trainer.py", line 472, in cloud_segmentation_validation
for i, batch in enumerate(val_loader):
File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in next
data = self._next_data()
File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
return self._process_data(data)
File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
data.reraise()
File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
data = fetcher.fetch(index)
File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/datasets/NPM3D.py", line 257, in getitem
return self.potential_item(batch_i)
File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/datasets/NPM3D.py", line 318, in potential_item
cloud_ind = int(torch.argmin(self.min_potentials))
RuntimeError: cannot perform reduction function argmin on a tensor with no elements because the operation does not have an identity

**Comment by HuguesTHOMAS** [comment]
Does `Vaihingen3D_test.ply` have labels or is it just a test cloud with points but no labels?

**Comment by HuguesTHOMAS** [comment]
Also can you show me what files are in the folder `input_0.200`?

**Comment by SC-shendazt** [comment]
yes，Vaihingen3D_test.ply have labels

**Comment by SC-shendazt** [comment]
![7(1)](https://user-images.githubusercontent.com/74888508/164753252-a337a1fe-e7dd-4641-b1e5-cf8c943347fc.jpg)

**Comment by HuguesTHOMAS** [comment]
Ok so the tensor `self.min_potentials` should be created, this is strange.\

Try to print what happens around here where min_potentials is created: 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/datasets/NPM3D.py#L192-L201

I can't spend much time on this so I am not going to trace back every error with you. I'll let you investigate the mistakes on your own, when an error arrives try to print stuff to understand what is wrong and trace back where the variables come from.

**Comment by SC-shendazt** [comment]
Thank you for your reply. I will try to trace the cause

**Comment by SC-shendazt** [comment]
When I printed  ‘self.min_potentials’,  I found that ‘self.min_potentials’ was empty inside and that the set validation was also empty，Perhaps I have set self.validation_split incorrectly?
![9](https://user-images.githubusercontent.com/74888508/164844505-a41f14f2-f57e-4948-9b9c-e049903b4e5f.png)
![8](https://user-images.githubusercontent.com/74888508/164844531-9ab14b93-0b51-402e-8868-503b2663a78f.png)

**Comment by SC-shendazt** [comment]
Hi Dr.HuguesTHOMAS, I have successfully run the Vaihingen _3D dataset, I set self.validation_split=1 and then added a '[ ]' at line 432 in the util\trainer.py module
![1](https://user-images.githubusercontent.com/74888508/164959869-6862945b-4f55-4412-b07e-2b517b8bfb03.png)
![2](https://user-images.githubusercontent.com/74888508/164959878-bc332cdf-d35b-479b-be98-645e8578c6c8.png)
![3](https://user-images.githubusercontent.com/74888508/164959880-ca41418f-79c6-4d11-a0ca-f6ae06ff03a4.png)

**Comment by HuguesTHOMAS** [comment]
Nice to hear that you solve the problem! :)

Are the results looking good?

**Comment by SC-shendazt** [comment]
Hi Dr.HuguesTHOMAS
Unfortunately, it doesn't seem to have any performance improvements, so I added EDGECONV and self -- Attention

**Comment by SC-shendazt** [comment]
Hi Dr.HuguesTHOMAS，It's me again. I have a new problem，I will show you the error message：I just wanted to rewrite a new BLOCK, but I found that the point clouds of the two tensors were inconsistent and I couldn't compute   
![QQ图片20220513000943](https://user-images.githubusercontent.com/74888508/168120575-9a6e441f-d908-4f6d-91ad-850f2903ae9a.png)
x+x1  
﻿Model Preparation
*****************
Done in 4.4s


Start training
**************
x.shape torch.Size([28175, 32])
x1.shape torch.Size([28175, 32])
x.shape torch.Size([28175, 32])
x1.shape torch.Size([28175, 32])
x.shape torch.Size([28175, 32])
x1.shape torch.Size([28175, 32])
x.shape torch.Size([28175, 32])
x1.shape torch.Size([28175, 32])
x.shape torch.Size([28175, 32])
x1.shape torch.Size([22371, 32])
Traceback (most recent call last):
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/train_S3DIS.py", line 357, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/utils/trainer.py", line 188, in train
    outputs = net(batch, config)
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/models/architectures.py", line 333, in forward
    x = block_op(x, batch)
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/models/blocks.py", line 738, in forward
    x1=self.Recurrent_block(x,batch)
  File "/home/zt/anaconda3/envs/torch37_2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/zt/D/PycharmProjects/KPConv-PyTorch-master/models/blocks.py", line 647, in forward
    x1=self.KPConv(q_pts, s_pts, neighb_inds,x+x1)
RuntimeError: The size of tensor a (28175) must match the size of tensor b (22371) at non-singleton dimension 0

**Comment by HuguesTHOMAS** [comment]
At this point because you are designing your own blocks, I can only try to guess what happens. From what I see, I think your block can only work on normal block and not on _strided_ blocks.

Strided blocks are reducing the number of points, as you can see at the beginning of your code the `if 'strided' ...` portion, the `q_pts` (query points) are different than the `s_pts` (support points). Therefore when you `x1` with the first KPConv, it will have a smaller dimension than `x`, hence the error.

I see two solutions:

a. just use a normal block for strided blocks and only use your custom block in between

b. If you want your block to work even when strided, adapt the implementation for this specific case. For example you can do the same as my ResNet block where I have a shortcut. When strided, I use a maxpooling to get the shortcut to the right amount of point before the addition:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/models/blocks.py#L641-L648

**Comment by SC-shendazt** [comment]
Dr.HuguesTHOMAS, I would like to show you my code. In the process of modification, I still encounter difficulties. I just want to add a cyclic residual structure, similar to Ru-UNet  

 def __init__(self,block_name, in_dim, out_dim, radius, layer_ind, config,t=3):
        super(Recurrent_block, self).__init__()
        # get KP_extent from current radius
        current_extent = radius * config.KP_extent / config.conv_radius
        # Get other parameters
        self.bn_momentum = config.batch_norm_momentum
        self.use_bn = config.use_batch_norm
        self.layer_ind = layer_ind
        self.block_name = block_name
        self.in_dim = in_dim
        self.out_dim = out_dim
        self.in_dim=self.out_dim
        self.t=t
        self.KPConv=KPConv(config.num_kernel_points,
                             config.in_points_dim,
                             in_dim,
                             out_dim,
                             current_extent,
                             radius,
                             fixed_kernel_points=config.fixed_kernel_points,
                             KP_influence=config.KP_influence,
                             aggregation_mode=config.aggregation_mode,
                             deformable='deform' in block_name,
                             modulated=config.modulated)
        self.batch_norm_conv = BatchNormBlock(out_dim, self.use_bn, self.bn_momentum)
        self.leaky_relu = nn.LeakyReLU(0.1)
        # Shortcut optional mpl
        if in_dim != out_dim:
            self.unary_shortcut = UnaryBlock(in_dim, out_dim, self.use_bn, self.bn_momentum, no_relu=True)
        else:
            self.unary_shortcut = nn.Identity()
    def forward(self,x,batch):
        if 'strided' in self.block_name:
            q_pts = batch.points[self.layer_ind + 1]
            s_pts = batch.points[self.layer_ind]
            neighb_inds = batch.pools[self.layer_ind]
        else:
            q_pts = batch.points[self.layer_ind]
            s_pts = batch.points[self.layer_ind]
            neighb_inds = batch.neighbors[self.layer_ind]
            # Shortcut
        if 'strided' in self.block_name:
            shortcut = max_pool(x, neighb_inds)
            print(shortcut.shape)
        else:
            shortcut = x
        shortcut = self.unary_shortcut(shortcut)
        x = shortcut
        for i in range(self.t):
            if i ==0:
                x1=self.KPConv(q_pts, s_pts, neighb_inds,x)
                # x1 = self.leaky_relu(self.batch_norm_conv(x1))
            print(x.shape,x1.shape)
            x1=self.KPConv(q_pts, s_pts, neighb_inds,x+x1)
            x1 = self.leaky_relu(self.batch_norm_conv(x1))
        return x1

**Comment by HuguesTHOMAS** [comment]
I am sorry, I don't have much time to help you throughout the whole process of designing these new blocks. This is really a research subject and it goes beyond the scope of Github issues where I try to help people use the code as-is.

I can take a few minutes as I did before to answer specific questions, but this is not the right place to give me your code for reviewing. The problem you are trying to solve is interesting, but I have my own projects. Try to test, debug, and answer the questions on your own, multiply the print statements, verify the output of every operation, etc. This is how I ended up with this KPConv repo, and I am sure you will be able to create your own blocks successfully.

Best of luck
Hugues

**Comment by SC-shendazt** [comment]
Dr.HuguesTHOMAS Thank you very much for your quick answer, I will follow your suggestions to improve this block
