### ISSUE TITLE
Problem with test_models.py

### ISSUE THREAD

**Issue by JohanBergius** [HuguesTHOMAS/KPConv-PyTorch#162]
Hi, Thomas. Would you be able to help me with another issue?  :)
I receive this problem during testing:

Done in 1.2s
e008-i0000 => 0.0% (timings : 65.56 47.31 93.94) / pots 8 => -14.4%
e008-i0006 => 13.3% (timings : 48.27 49.72 103.27) / pots 8 => -2.7%
e008-i0012 => 26.7% (timings : 35.56 50.56 118.99) / pots 8 => 9.0%
e008-i0018 => 40.0% (timings : 26.21 51.91 120.31) / pots 8 => 20.7%
e008-i0025 => 55.6% (timings : 18.43 51.46 116.98) / pots 8 => 34.4%
e008-i0029 => 64.4% (timings : 15.06 51.23 142.65) / pots 8 => 42.2%
e008-i0033 => 73.3% (timings : 12.31 51.37 155.29) / pots 8 => 50.0%
Traceback (most recent call last):
  File "test_models.py", line 225, in <module>
    tester.slam_segmentation_test(net, test_loader, config)
  File "/home/stud2/j/johanb17/KPConv-PyTorch-master/utils/tester.py", line 527, in slam_                                                                                                                                                    segmentation_test
    for i, batch in enumerate(test_loader):
  File "/home/stud/j/johanb17/.conda/envs/KPmlp/lib/python3.6/site-packages/torch/utils/d                                                                                                                                                    ata/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/stud/j/johanb17/.conda/envs/KPmlp/lib/python3.6/site-packages/torch/utils/d                                                                                                                                                    ata/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/stud/j/johanb17/.conda/envs/KPmlp/lib/python3.6/site-packages/torch/utils/d                                                                                                                                                    ata/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/stud/j/johanb17/.conda/envs/KPmlp/lib/python3.6/site-packages/torch/_utils.                                                                                                                                                    py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/stud/j/johanb17/.conda/envs/KPmlp/lib/python3.6/site-packages/torch/utils/d                                                                                                                                                    ata/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/stud/j/johanb17/.conda/envs/KPmlp/lib/python3.6/site-packages/torch/utils/d                                                                                                                                                    ata/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/stud/j/johanb17/.conda/envs/KPmlp/lib/python3.6/site-packages/torch/utils/d                                                                                                                                                    ata/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/stud2/j/johanb17/KPConv-PyTorch-master/datasets/SemanticKitti.py", line 244                                                                                                                                                    , in __getitem__
    ind = int(self.epoch_inds[self.epoch_i])
IndexError: index 397 is out of bounds for dimension 0 with size 397

**Comment by JohanBergius** [comment]
The problem seems to be that  397 is the length of self.epoch_inds, but my test-set size is 410! Any ideas?
