### ISSUE TITLE
size error when test model by test_model.py

### ISSUE THREAD

**Issue by Trexzhou** [HuguesTHOMAS/KPConv-PyTorch#182]
Hi HuguesTHOMAS! Thank you for your nice work!
I followed "slam_segmentation_guide.md" and successfully train the model in my own data set(A data set with the same format as a SemanticKitti). When I want to test the model by run "python3 test_any_model.py", the following error appears:

Initialize workers
Traceback (most recent call last):
  File "test_models.py", line 217, in <module>
    tester.slam_segmentation_test(net, test_loader, config)
  File "/home/jovyan/KPConv-PyTorch/utils/tester.py", line 527, in slam_segmentation_test
    for i, batch in enumerate(test_loader):
  File "/home/jovyan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/jovyan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/jovyan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/home/jovyan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/home/jovyan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/home/jovyan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/jovyan/.local/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/jovyan/project/zhoujianbin/KPConv-PyTorch/datasets/SemanticKitti.py", line 880, in __iter__
    self.dataset.epoch_inds += gen_indices
RuntimeError: The size of tensor a (1761) must match the size of tensor b (78) at non-singleton dimension 0

I want to know what caused it? Appreciate for your nice work again!

**Comment by Trexzhou** [comment]
![image](https://user-images.githubusercontent.com/40020015/177161842-c6df587c-aba2-4ef9-b9fe-5fea0b6ebfba.png)
Here is my custom semantic-kitti.yaml file, the test set's size is 78。

**Comment by working12** [comment]
Can you provide us with the details of how you fixed it?
