### ISSUE TITLE
Invalid argument in training?

### ISSUE THREAD

**Issue by cloud-cove** [HuguesTHOMAS/KPConv-PyTorch#234]
Hello! I'm trying to use this project, and am encountering an error when I try to run the train_S3DIS.py, the program gets through the Data Preparation and calibration, and Model Preparation, but when it starts training I encounter this error. I'm not sure what could be wrong, could someone point me in the right direction? I'm using Windows (unforunately). Thanks for any pointers anyone can give!

> 
Model Preparation

Done in 0.6s

Start training

Traceback (most recent call last):
  File "C:\00stuff\ImgProc\projectwork\Experiments\KPConv-PyTorch\train_S3DIS.py", line 328, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "C:\00stuff\ImgProc\projectwork\Experiments\KPConv-PyTorch\utils\trainer.py", line 167, in train
    for batch in training_loader:
  File "C:\00stuff\pythonese\projectenv310\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "C:\00stuff\pythonese\projectenv310\lib\site-packages\torch\utils\data\dataloader.py", line 386, in _get_iterator    return _MultiProcessingDataLoaderIter(self)
  File "C:\00stuff\pythonese\projectenv310\lib\site-packages\torch\utils\data\dataloader.py", line 1039, in __init__
    w.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

Edit: after some investigating I think this might be because my batch_limit.pkl file is only 1 KB and is probably empty? What should be in that file?

**Comment by cloud-cove** [comment]
Fixed, none of the cuda commands worked for me so i needed to set each instance of num_workers = 0
