### ISSUE TITLE
Error: 'list' object has no attribute 'clone' while executing train_S3DIS

### ISSUE THREAD

**Issue by Arjun-NA** [HuguesTHOMAS/KPConv-PyTorch#39]
Hi @HuguesTHOMAS , 
I was trying to run the S3DIS for just area1 and area2 

I changed the following in datasets/S3DIS.py
```
        self.cloud_names = ['Area_1', 'Area_2' ] #, 'Area_3', 'Area_4', 'Area_5', 'Area_6']
        self.all_splits = [0, 1] # 2, 3, 4, 5]
```

But I run in to the following error
**AttributeError: 'list' object has no attribute 'clone'**
```
Start training
**************
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/kpconv/KPConv-PyTorch-master/train_S3DIS.py", line 304, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "E:\kpconv\KPConv-PyTorch-master\utils\trainer.py", line 188, in train
    outputs = net(batch, config)
  File "P:\Anaconda_installation\envs\aero\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\kpconv\KPConv-PyTorch-master\models\architectures.py", line 325, in forward
    x = batch.points.clone().detach()
AttributeError: 'list' object has no attribute 'clone'

```

Kindly let me know what I should do to resolve this error.

Thanks,
Arjun.

**Comment by HuguesTHOMAS** [comment]
Maybe that is related to the validation split. I usually is Area_5. Did you change it?

If you have no validation, I am not sure the code can handle it in the current implementation.

**Comment by Arjun-NA** [comment]
`self.validation_split = 0` 
Validation is set to take in Area 0
I will anyways run the whole dataset to see if that will change the problem.

**Comment by HuguesTHOMAS** [comment]
I think you modified a line of the code and this is why you have an error. Your error message says 

> File "E:\kpconv\KPConv-PyTorch-master\models\architectures.py", line 325, in forward
    x = batch.points.clone().detach()
AttributeError: 'list' object has no attribute 'clone'

But in the original code, the line 325 of architectures.py is:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/models/architectures.py#L325

You should not use the `batch.points` as input features. If your goal is to have points coordinates as features, just copy them in the `batch.features` tensor.

**Comment by Arjun-NA** [comment]
Hey, I actually tried running the full S3DIS dataset and run it to the same error. I am not sure why.
The following is the full log. Area 1 and 2 was done previously so it started preparing data from Area 3 onwards.

```
P:\Anaconda_installation\envs\aero\python.exe E:/kpconv/KPConv-PyTorch-master/train_S3DIS.py

Data Preparation
****************

Preparing ply files
Cloud Area_3 - Room 1/23 : S3DIS\Area_3\conferenceRoom_1
Cloud Area_3 - Room 2/23 : S3DIS\Area_3\hallway_1
Cloud Area_3 - Room 3/23 : S3DIS\Area_3\hallway_2
Cloud Area_3 - Room 4/23 : S3DIS\Area_3\hallway_3
Cloud Area_3 - Room 5/23 : S3DIS\Area_3\hallway_4
Cloud Area_3 - Room 6/23 : S3DIS\Area_3\hallway_5
Cloud Area_3 - Room 7/23 : S3DIS\Area_3\hallway_6
Cloud Area_3 - Room 8/23 : S3DIS\Area_3\lounge_1
Cloud Area_3 - Room 9/23 : S3DIS\Area_3\lounge_2
Cloud Area_3 - Room 10/23 : S3DIS\Area_3\office_1
Cloud Area_3 - Room 11/23 : S3DIS\Area_3\office_10
Cloud Area_3 - Room 12/23 : S3DIS\Area_3\office_2
Cloud Area_3 - Room 13/23 : S3DIS\Area_3\office_3
Cloud Area_3 - Room 14/23 : S3DIS\Area_3\office_4
Cloud Area_3 - Room 15/23 : S3DIS\Area_3\office_5
Cloud Area_3 - Room 16/23 : S3DIS\Area_3\office_6
Cloud Area_3 - Room 17/23 : S3DIS\Area_3\office_7
Cloud Area_3 - Room 18/23 : S3DIS\Area_3\office_8
Cloud Area_3 - Room 19/23 : S3DIS\Area_3\office_9
Cloud Area_3 - Room 20/23 : S3DIS\Area_3\storage_1
Cloud Area_3 - Room 21/23 : S3DIS\Area_3\storage_2
Cloud Area_3 - Room 22/23 : S3DIS\Area_3\WC_1
Cloud Area_3 - Room 23/23 : S3DIS\Area_3\WC_2
Cloud Area_4 - Room 1/49 : S3DIS\Area_4\conferenceRoom_1
Cloud Area_4 - Room 2/49 : S3DIS\Area_4\conferenceRoom_2
Cloud Area_4 - Room 3/49 : S3DIS\Area_4\conferenceRoom_3
Cloud Area_4 - Room 4/49 : S3DIS\Area_4\hallway_1
Cloud Area_4 - Room 5/49 : S3DIS\Area_4\hallway_10
Cloud Area_4 - Room 6/49 : S3DIS\Area_4\hallway_11
Cloud Area_4 - Room 7/49 : S3DIS\Area_4\hallway_12
Cloud Area_4 - Room 8/49 : S3DIS\Area_4\hallway_13
Cloud Area_4 - Room 9/49 : S3DIS\Area_4\hallway_14
Cloud Area_4 - Room 10/49 : S3DIS\Area_4\hallway_2
Cloud Area_4 - Room 11/49 : S3DIS\Area_4\hallway_3
Cloud Area_4 - Room 12/49 : S3DIS\Area_4\hallway_4
Cloud Area_4 - Room 13/49 : S3DIS\Area_4\hallway_5
Cloud Area_4 - Room 14/49 : S3DIS\Area_4\hallway_6
Cloud Area_4 - Room 15/49 : S3DIS\Area_4\hallway_7
Cloud Area_4 - Room 16/49 : S3DIS\Area_4\hallway_8
Cloud Area_4 - Room 17/49 : S3DIS\Area_4\hallway_9
Cloud Area_4 - Room 18/49 : S3DIS\Area_4\lobby_1
Cloud Area_4 - Room 19/49 : S3DIS\Area_4\lobby_2
Cloud Area_4 - Room 20/49 : S3DIS\Area_4\office_1
Cloud Area_4 - Room 21/49 : S3DIS\Area_4\office_10
Cloud Area_4 - Room 22/49 : S3DIS\Area_4\office_11
Cloud Area_4 - Room 23/49 : S3DIS\Area_4\office_12
Cloud Area_4 - Room 24/49 : S3DIS\Area_4\office_13
Cloud Area_4 - Room 25/49 : S3DIS\Area_4\office_14
Cloud Area_4 - Room 26/49 : S3DIS\Area_4\office_15
Cloud Area_4 - Room 27/49 : S3DIS\Area_4\office_16
Cloud Area_4 - Room 28/49 : S3DIS\Area_4\office_17
Cloud Area_4 - Room 29/49 : S3DIS\Area_4\office_18
Cloud Area_4 - Room 30/49 : S3DIS\Area_4\office_19
Cloud Area_4 - Room 31/49 : S3DIS\Area_4\office_2
Cloud Area_4 - Room 32/49 : S3DIS\Area_4\office_20
Cloud Area_4 - Room 33/49 : S3DIS\Area_4\office_21
Cloud Area_4 - Room 34/49 : S3DIS\Area_4\office_22
Cloud Area_4 - Room 35/49 : S3DIS\Area_4\office_3
Cloud Area_4 - Room 36/49 : S3DIS\Area_4\office_4
Cloud Area_4 - Room 37/49 : S3DIS\Area_4\office_5
Cloud Area_4 - Room 38/49 : S3DIS\Area_4\office_6
Cloud Area_4 - Room 39/49 : S3DIS\Area_4\office_7
Cloud Area_4 - Room 40/49 : S3DIS\Area_4\office_8
Cloud Area_4 - Room 41/49 : S3DIS\Area_4\office_9
Cloud Area_4 - Room 42/49 : S3DIS\Area_4\storage_1
Cloud Area_4 - Room 43/49 : S3DIS\Area_4\storage_2
Cloud Area_4 - Room 44/49 : S3DIS\Area_4\storage_3
Cloud Area_4 - Room 45/49 : S3DIS\Area_4\storage_4
Cloud Area_4 - Room 46/49 : S3DIS\Area_4\WC_1
Cloud Area_4 - Room 47/49 : S3DIS\Area_4\WC_2
Cloud Area_4 - Room 48/49 : S3DIS\Area_4\WC_3
Cloud Area_4 - Room 49/49 : S3DIS\Area_4\WC_4
Cloud Area_5 - Room 1/68 : S3DIS\Area_5\conferenceRoom_1
Cloud Area_5 - Room 2/68 : S3DIS\Area_5\conferenceRoom_2
Cloud Area_5 - Room 3/68 : S3DIS\Area_5\conferenceRoom_3
Cloud Area_5 - Room 4/68 : S3DIS\Area_5\hallway_1
Cloud Area_5 - Room 5/68 : S3DIS\Area_5\hallway_10
Cloud Area_5 - Room 6/68 : S3DIS\Area_5\hallway_11
Cloud Area_5 - Room 7/68 : S3DIS\Area_5\hallway_12
Cloud Area_5 - Room 8/68 : S3DIS\Area_5\hallway_13
Cloud Area_5 - Room 9/68 : S3DIS\Area_5\hallway_14
Cloud Area_5 - Room 10/68 : S3DIS\Area_5\hallway_15
Cloud Area_5 - Room 11/68 : S3DIS\Area_5\hallway_2
Cloud Area_5 - Room 12/68 : S3DIS\Area_5\hallway_3
Cloud Area_5 - Room 13/68 : S3DIS\Area_5\hallway_4
Cloud Area_5 - Room 14/68 : S3DIS\Area_5\hallway_5
Cloud Area_5 - Room 15/68 : S3DIS\Area_5\hallway_6
Cloud Area_5 - Room 16/68 : S3DIS\Area_5\hallway_7
Cloud Area_5 - Room 17/68 : S3DIS\Area_5\hallway_8
Cloud Area_5 - Room 18/68 : S3DIS\Area_5\hallway_9
Cloud Area_5 - Room 19/68 : S3DIS\Area_5\lobby_1
Cloud Area_5 - Room 20/68 : S3DIS\Area_5\office_1
Cloud Area_5 - Room 21/68 : S3DIS\Area_5\office_10
Cloud Area_5 - Room 22/68 : S3DIS\Area_5\office_11
Cloud Area_5 - Room 23/68 : S3DIS\Area_5\office_12
Cloud Area_5 - Room 24/68 : S3DIS\Area_5\office_13
Cloud Area_5 - Room 25/68 : S3DIS\Area_5\office_14
Cloud Area_5 - Room 26/68 : S3DIS\Area_5\office_15
Cloud Area_5 - Room 27/68 : S3DIS\Area_5\office_16
Cloud Area_5 - Room 28/68 : S3DIS\Area_5\office_17
Cloud Area_5 - Room 29/68 : S3DIS\Area_5\office_18
Cloud Area_5 - Room 30/68 : S3DIS\Area_5\office_19
Cloud Area_5 - Room 31/68 : S3DIS\Area_5\office_2
Cloud Area_5 - Room 32/68 : S3DIS\Area_5\office_20
Cloud Area_5 - Room 33/68 : S3DIS\Area_5\office_21
Cloud Area_5 - Room 34/68 : S3DIS\Area_5\office_22
Cloud Area_5 - Room 35/68 : S3DIS\Area_5\office_23
Cloud Area_5 - Room 36/68 : S3DIS\Area_5\office_24
Cloud Area_5 - Room 37/68 : S3DIS\Area_5\office_25
Cloud Area_5 - Room 38/68 : S3DIS\Area_5\office_26
Cloud Area_5 - Room 39/68 : S3DIS\Area_5\office_27
Cloud Area_5 - Room 40/68 : S3DIS\Area_5\office_28
Cloud Area_5 - Room 41/68 : S3DIS\Area_5\office_29
Cloud Area_5 - Room 42/68 : S3DIS\Area_5\office_3
Cloud Area_5 - Room 43/68 : S3DIS\Area_5\office_30
Cloud Area_5 - Room 44/68 : S3DIS\Area_5\office_31
Cloud Area_5 - Room 45/68 : S3DIS\Area_5\office_32
Cloud Area_5 - Room 46/68 : S3DIS\Area_5\office_33
Cloud Area_5 - Room 47/68 : S3DIS\Area_5\office_34
Cloud Area_5 - Room 48/68 : S3DIS\Area_5\office_35
Cloud Area_5 - Room 49/68 : S3DIS\Area_5\office_36
Cloud Area_5 - Room 50/68 : S3DIS\Area_5\office_37
Cloud Area_5 - Room 51/68 : S3DIS\Area_5\office_38
Cloud Area_5 - Room 52/68 : S3DIS\Area_5\office_39
Cloud Area_5 - Room 53/68 : S3DIS\Area_5\office_4
Cloud Area_5 - Room 54/68 : S3DIS\Area_5\office_40
Cloud Area_5 - Room 55/68 : S3DIS\Area_5\office_41
Cloud Area_5 - Room 56/68 : S3DIS\Area_5\office_42
Cloud Area_5 - Room 57/68 : S3DIS\Area_5\office_5
Cloud Area_5 - Room 58/68 : S3DIS\Area_5\office_6
Cloud Area_5 - Room 59/68 : S3DIS\Area_5\office_7
Cloud Area_5 - Room 60/68 : S3DIS\Area_5\office_8
Cloud Area_5 - Room 61/68 : S3DIS\Area_5\office_9
Cloud Area_5 - Room 62/68 : S3DIS\Area_5\pantry_1
Cloud Area_5 - Room 63/68 : S3DIS\Area_5\storage_1
Cloud Area_5 - Room 64/68 : S3DIS\Area_5\storage_2
Cloud Area_5 - Room 65/68 : S3DIS\Area_5\storage_3
Cloud Area_5 - Room 66/68 : S3DIS\Area_5\storage_4
Cloud Area_5 - Room 67/68 : S3DIS\Area_5\WC_1
Cloud Area_5 - Room 68/68 : S3DIS\Area_5\WC_2
Cloud Area_6 - Room 1/48 : S3DIS\Area_6\conferenceRoom_1
Cloud Area_6 - Room 2/48 : S3DIS\Area_6\copyRoom_1
Cloud Area_6 - Room 3/48 : S3DIS\Area_6\hallway_1
Cloud Area_6 - Room 4/48 : S3DIS\Area_6\hallway_2
Cloud Area_6 - Room 5/48 : S3DIS\Area_6\hallway_3
Cloud Area_6 - Room 6/48 : S3DIS\Area_6\hallway_4
Cloud Area_6 - Room 7/48 : S3DIS\Area_6\hallway_5
Cloud Area_6 - Room 8/48 : S3DIS\Area_6\hallway_6
Cloud Area_6 - Room 9/48 : S3DIS\Area_6\lounge_1
Cloud Area_6 - Room 10/48 : S3DIS\Area_6\office_1
Cloud Area_6 - Room 11/48 : S3DIS\Area_6\office_10
Cloud Area_6 - Room 12/48 : S3DIS\Area_6\office_11
Cloud Area_6 - Room 13/48 : S3DIS\Area_6\office_12
Cloud Area_6 - Room 14/48 : S3DIS\Area_6\office_13
Cloud Area_6 - Room 15/48 : S3DIS\Area_6\office_14
Cloud Area_6 - Room 16/48 : S3DIS\Area_6\office_15
Cloud Area_6 - Room 17/48 : S3DIS\Area_6\office_16
Cloud Area_6 - Room 18/48 : S3DIS\Area_6\office_17
Cloud Area_6 - Room 19/48 : S3DIS\Area_6\office_18
Cloud Area_6 - Room 20/48 : S3DIS\Area_6\office_19
Cloud Area_6 - Room 21/48 : S3DIS\Area_6\office_2
Cloud Area_6 - Room 22/48 : S3DIS\Area_6\office_20
Cloud Area_6 - Room 23/48 : S3DIS\Area_6\office_21
Cloud Area_6 - Room 24/48 : S3DIS\Area_6\office_22
Cloud Area_6 - Room 25/48 : S3DIS\Area_6\office_23
Cloud Area_6 - Room 26/48 : S3DIS\Area_6\office_24
Cloud Area_6 - Room 27/48 : S3DIS\Area_6\office_25
Cloud Area_6 - Room 28/48 : S3DIS\Area_6\office_26
Cloud Area_6 - Room 29/48 : S3DIS\Area_6\office_27
Cloud Area_6 - Room 30/48 : S3DIS\Area_6\office_28
Cloud Area_6 - Room 31/48 : S3DIS\Area_6\office_29
Cloud Area_6 - Room 32/48 : S3DIS\Area_6\office_3
Cloud Area_6 - Room 33/48 : S3DIS\Area_6\office_30
Cloud Area_6 - Room 34/48 : S3DIS\Area_6\office_31
Cloud Area_6 - Room 35/48 : S3DIS\Area_6\office_32
Cloud Area_6 - Room 36/48 : S3DIS\Area_6\office_33
Cloud Area_6 - Room 37/48 : S3DIS\Area_6\office_34
Cloud Area_6 - Room 38/48 : S3DIS\Area_6\office_35
Cloud Area_6 - Room 39/48 : S3DIS\Area_6\office_36
Cloud Area_6 - Room 40/48 : S3DIS\Area_6\office_37
Cloud Area_6 - Room 41/48 : S3DIS\Area_6\office_4
Cloud Area_6 - Room 42/48 : S3DIS\Area_6\office_5
Cloud Area_6 - Room 43/48 : S3DIS\Area_6\office_6
Cloud Area_6 - Room 44/48 : S3DIS\Area_6\office_7
Cloud Area_6 - Room 45/48 : S3DIS\Area_6\office_8
Cloud Area_6 - Room 46/48 : S3DIS\Area_6\office_9
Cloud Area_6 - Room 47/48 : S3DIS\Area_6\openspace_1
Cloud Area_6 - Room 48/48 : S3DIS\Area_6\pantry_1
Done in 3429.1s

Found KDTree for cloud Area_2, subsampled at 0.030
159.1 MB loaded in 3.6s

Preparing KDTree for cloud Area_3, subsampled at 0.030
62.6 MB loaded in 11.1s

Preparing KDTree for cloud Area_4, subsampled at 0.030
144.2 MB loaded in 27.7s

Preparing KDTree for cloud Area_5, subsampled at 0.030
260.4 MB loaded in 55.9s

Preparing KDTree for cloud Area_6, subsampled at 0.030
137.9 MB loaded in 30.5s

Preparing potentials
Done in 4.4s


Preparing ply files
Done in 0.0s

Found KDTree for cloud Area_1, subsampled at 0.030
146.6 MB loaded in 3.2s

Preparing potentials
Done in 0.1s

Preparing reprojection indices for testing
Area_1 done in 2.8s


Starting Calibration (use verbose=True for more details)

Previous calibration found:
Check batch limit dictionary
"potentials_1.500_0.030_6": 75901
Check neighbors limit dictionary
"0.030_0.075": 29
"0.060_0.150": 31
"0.120_0.720": 247
"0.240_1.440": 218
"0.480_2.880": 102
Calibration done in 0.1s


Starting Calibration (use verbose=True for more details)

Previous calibration found:
Check batch limit dictionary
"potentials_1.500_0.030_6": 75901
Check neighbors limit dictionary
"0.030_0.075": 29
"0.060_0.150": 31
"0.120_0.720": 247
"0.240_1.440": 218
"0.480_2.880": 102
Calibration done in 0.0s


Model Preparation
*****************
Done in 13.3s


Start training
**************
Traceback (most recent call last):
  File "E:/kpconv/KPConv-PyTorch-master/train_S3DIS.py", line 304, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "E:\kpconv\KPConv-PyTorch-master\utils\trainer.py", line 188, in train
    outputs = net(batch, config)
  File "P:\Anaconda_installation\envs\aero\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\kpconv\KPConv-PyTorch-master\models\architectures.py", line 325, in forward
    x = batch.points.clone().detach()
AttributeError: 'list' object has no attribute 'clone'

Process finished with exit code 1
```

**Comment by Arjun-NA** [comment]
Oh Okay Thank you so much,
I am sorry I don't know why it got changed.
