### ISSUE TITLE
creating Batchlimits.pkl error 

### ISSUE THREAD

**Issue by Arjun-NA** [HuguesTHOMAS/KPConv-PyTorch#63]
Hi,

As I was trying to create a database file for Dales similar to S3DIS, I find that the code search for a Batchlimits.pkl and a neighborhoodlimits.pkl. For the datasets like ModelNet40, these files already exists and runs into no error. but once these files are removed though there is code to redo this. That part is not working. Please see the error below. There's memory error. I use 32GB ram but still fails thought the dataset only requires around 15GB in the RAM.  

```
Traceback (most recent call last):
  File "P:\Anaconda_installation\envs\aero\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "P:\Anaconda_installation\envs\aero\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
MemoryError
Traceback (most recent call last):
  File "P:\Anaconda_installation\envs\aero\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

I also get OSError sometimes in the same point 
``` 
ForkingPickler(file, protocol).dump(obj)
```

Please let me know the aim of the code in calibration and if there's any other memory effective way to approach this.

Thanks,
Arjun.

**Comment by Arjun-NA** [comment]
I am sorry it works for modelnet40. just not for the which i am trying to make.
