### ISSUE TITLE
Error when run "train_S3DIS.py"

### ISSUE THREAD

**Issue by dcy0577** [HuguesTHOMAS/KPConv-PyTorch#94]
Hi @HuguesTHOMAS,

I got some error when run 'python train_S3DIS.py'. I noticed that this error is similar with the one in this issue:  https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/1#issue-613750558
My environment is ubuntu16.04, python=3.6, pytorch=1.2.0, cuda=10.0.
Could you please tell me which lines of code should be changed to solve this data type problem? Thanks!

```
Starting Calibration (use verbose=True for more details)

Previous calibration found:
Check batch limit dictionary
"potentials_1.500_0.030_6": ?
Check neighbors limit dictionary
"0.030_0.075": ?
"0.060_0.150": ?
"0.120_0.720": ?
"0.240_1.440": ?
"0.480_2.880": ?
Traceback (most recent call last):
  File "train_S3DIS.py", line 269, in <module>
    training_sampler.calibration(training_loader, verbose=True)
  File "/home/dchangyu/mvpnet/KPConv-PyTorch/datasets/S3DIS.py", line 1181, in calibration
    for batch_i, batch in enumerate(dataloader):
  File "/home/dchangyu/miniconda3/envs/mvpnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/dchangyu/miniconda3/envs/mvpnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/dchangyu/miniconda3/envs/mvpnet/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dchangyu/miniconda3/envs/mvpnet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dchangyu/miniconda3/envs/mvpnet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dchangyu/miniconda3/envs/mvpnet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dchangyu/mvpnet/KPConv-PyTorch/datasets/S3DIS.py", line 240, in __getitem__
    return self.potential_item(batch_i)
  File "/home/dchangyu/mvpnet/KPConv-PyTorch/datasets/S3DIS.py", line 325, in potential_item
    self.potentials[cloud_ind][pot_inds] += tukeys
TypeError: add_(): argument 'other' (position 1) must be Tensor, not numpy.ndarray
```

**Comment by HuguesTHOMAS** [comment]
Hi @dcy0577,

This error is strange, and I think could be caused by your old version of PyTorch. 

>   File "/home/dchangyu/mvpnet/KPConv-PyTorch/datasets/S3DIS.py", line 325, in potential_item
>     self.potentials[cloud_ind][pot_inds] += tukeys

It seems the addition of a tensor and an np.array is not allowed. You can correct this by using `torch.from_numpy` on the array called `tukeys`. But there might be other errors that occurs due to the old PyTorch version. I strongly advise upgrading to PyTorch 1.4 (or higher) to be sure you don't have any other errors.

Best,
Hugues

**Comment by dcy0577** [comment]
Hi @HuguesTHOMAS, thanks a lot for the quick reply, the training works now. By the way, I later encountered another data format error and I have solved it by simply adding `long()` behind `neighb_row_bool`  (might be useful for someone who also use the old version of Pytorch)
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/7fefb6a8d38fd304775199777ad01d9f1546e2ff/models/blocks.py#L323
