### ISSUE TITLE
S3DIS training: The size of tensor a (3000) must match the size of tensor b (300) at non-singleton dimension 1

### ISSUE THREAD

**Issue by decadenza** [HuguesTHOMAS/KPConv-PyTorch#98]
Hi.
I launched train_S3DIS.py, after the training started I got:

```
Traceback (most recent call last):
  File "/Code/DentFCN/KPConv/Experiments/KPConv/train_S3DIS.py", line 304, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "/Code/DentFCN/KPConv/Experiments/KPConv/utils/trainer.py", line 271, in train
    self.validation(net, val_loader, config)
  File "/Code/DentFCN/KPConv/Experiments/KPConv/utils/trainer.py", line 287, in validation
    self.cloud_segmentation_validation(net, val_loader, config)
  File "/Code/DentFCN/KPConv/Experiments/KPConv/utils/trainer.py", line 468, in cloud_segmentation_validation
    for i, batch in enumerate(val_loader):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 940, in __init__
    self._reset(loader, first_iter=True)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 971, in _reset
    self._try_put_index()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1205, in _try_put_index
    index = self._next_index()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/Code/DentFCN/KPConv/Experiments/KPConv/datasets/S3DIS.py", line 949, in __iter__
    self.dataset.epoch_inds += torch.from_numpy(all_epoch_inds[:, :num_centers])
RuntimeError: The size of tensor a (3000) must match the size of tensor b (300) at non-singleton dimension 1
```

I've made the following changes to the original code:
`use_potentials=False`
`in_radius = 0.5`

Cheers

**Comment by PPPPeterpan** [comment]
Hi,
did you solve this problem? got the same problem when changing use_potentials=False
thanks!

**Comment by decadenza** [comment]
Nope. I switched to another approach.

**Comment by HuguesTHOMAS** [comment]
Hi @decadenza and @PPPPeterpan,

I found the problem and made a correction.

Just a note though, this error happens when you used `use_potentials=False` on the validation dataset, which is not advised as the test spheres will not be ensured to cover the whole test area.
